#!/usr/bin/env python3
"""
blogger-radar / scripts / pushers / discord_pusher.py
Push the daily report to a Discord channel via Webhook.

Setup:
  1. Open your Discord server → Channel Settings → Integrations → Webhooks
  2. Create a new webhook, name it "Blogger Radar"
  3. Copy the Webhook URL
  4. Set DISCORD_WEBHOOK_URL in your .env file

Config entry in ~/.blogger-radar/config.json:
  { "channel": "discord", "enabled": true }

Environment variable required:
  DISCORD_WEBHOOK_URL
"""

import logging
from datetime import datetime

import httpx

log = logging.getLogger(__name__)

# Discord embed description limit is 4096 chars; stay below it
EMBED_CHAR_LIMIT = 3900
# Discord allows up to 10 embeds per message
MAX_EMBEDS = 10


class DiscordPusher:
    def __init__(self, cfg: dict) -> None:
        self.webhook_url = cfg.get("webhook_url", "")
        self.username = cfg.get("username", "Blogger Radar")
        self.avatar_url = cfg.get("avatar_url", "")

    async def push(self, report: dict) -> bool:
        if not self.webhook_url:
            log.error("❌ DISCORD_WEBHOOK_URL not set")
            return False

        markdown = report.get("markdown", "")
        date_str = report.get("date", datetime.now().strftime("%Y-%m-%d"))
        blogger_count = report.get("blogger_count", "?")

        embeds = self._build_embeds(markdown, date_str, blogger_count)

        payload = {
            "username": self.username,
            "embeds": embeds[:MAX_EMBEDS],
        }
        if self.avatar_url:
            payload["avatar_url"] = self.avatar_url

        try:
            async with httpx.AsyncClient(timeout=15) as client:
                resp = await client.post(self.webhook_url, json=payload)
                if resp.status_code in (200, 204):
                    log.info("✓ Discord push success")
                    return True
                else:
                    log.error(f"✗ Discord returned {resp.status_code}: {resp.text}")
                    return False
        except Exception as e:
            log.error(f"✗ Discord push error: {e}")
            return False

    def _build_embeds(self, markdown: str, date_str: str, blogger_count) -> list:
        """Convert report markdown into Discord embeds (one per blogger)."""
        embeds = []

        # Header embed
        embeds.append(
            {
                "title": f"📡 Blogger Radar — {date_str}",
                "description": f"Tracking **{blogger_count}** creator(s) · Generated by Blogger Radar",
                "color": 0x5865F2,  # Discord blurple
            }
        )

        # One embed per blogger section
        sections = markdown.split("\n## ")
        for section in sections[1:]:
            lines = section.strip().splitlines()
            if not lines:
                continue
            title = lines[0].strip()
            body = "\n".join(lines[1:]).strip()

            if len(body) > EMBED_CHAR_LIMIT:
                body = body[:EMBED_CHAR_LIMIT] + "\n*(truncated)*"

            embeds.append(
                {
                    "title": title,
                    "description": body,
                    "color": 0x57F287,  # green
                }
            )

        return embeds
