#!/usr/bin/env python3
"""
blogger-radar / scripts / pushers / feishu_pusher.py
Push the daily report to a Feishu (Lark) group via Custom Bot Webhook.

Setup:
  1. Open your Feishu group chat → Settings → Bots → Add Bot → Custom Bot
  2. Name it "Blogger Radar", finish setup
  3. Copy the Webhook URL (https://open.feishu.cn/open-apis/bot/v2/hook/...)
  4. Set FEISHU_WEBHOOK_URL in your .env file
  5. If signature verification is enabled, also set FEISHU_BOT_SECRET

Config entry in ~/.blogger-radar/config.json:
  { "channel": "feishu", "enabled": true }

Environment variables required:
  FEISHU_WEBHOOK_URL

Optional:
  FEISHU_BOT_SECRET   (if signature verification is enabled in the bot settings)
"""

import hashlib
import hmac
import base64
import logging
import time
from datetime import datetime

import httpx

log = logging.getLogger(__name__)

MSG_CHAR_LIMIT = 4000  # Feishu markdown card body limit (approximate)


class FeishuPusher:
    def __init__(self, cfg: dict) -> None:
        self.webhook_url = cfg.get("webhook_url", "")
        self.secret = cfg.get("secret", "")  # optional signature secret

    async def push(self, report: dict) -> bool:
        if not self.webhook_url:
            log.error("❌ FEISHU_WEBHOOK_URL not set")
            return False

        markdown = report.get("markdown", "")
        date_str = report.get("date", datetime.now().strftime("%Y-%m-%d"))
        blogger_count = report.get("blogger_count", "?")

        body = self._build_payload(markdown, date_str, blogger_count)

        if self.secret:
            timestamp = str(int(time.time()))
            body["timestamp"] = timestamp
            body["sign"] = self._sign(timestamp)

        try:
            async with httpx.AsyncClient(timeout=15) as client:
                resp = await client.post(self.webhook_url, json=body)
                data = resp.json()
                if data.get("code") == 0 or data.get("StatusCode") == 0:
                    log.info("✓ Feishu push success")
                    return True
                else:
                    log.error(f"✗ Feishu returned: {data}")
                    return False
        except Exception as e:
            log.error(f"✗ Feishu push error: {e}")
            return False

    def _build_payload(self, markdown: str, date_str: str, blogger_count) -> dict:
        """Build a Feishu interactive card message."""
        content = markdown
        if len(content) > MSG_CHAR_LIMIT:
            content = content[:MSG_CHAR_LIMIT] + "\n\n_(report truncated)_"

        return {
            "msg_type": "interactive",
            "card": {
                "config": {"wide_screen_mode": True},
                "header": {
                    "title": {
                        "tag": "plain_text",
                        "content": f"📡 Blogger Radar — {date_str}",
                    },
                    "template": "blue",
                },
                "elements": [
                    {
                        "tag": "div",
                        "text": {
                            "tag": "lark_md",
                            "content": f"Tracking **{blogger_count}** creator(s)",
                        },
                    },
                    {"tag": "hr"},
                    {
                        "tag": "div",
                        "text": {
                            "tag": "lark_md",
                            "content": content,
                        },
                    },
                    {
                        "tag": "note",
                        "elements": [
                            {
                                "tag": "plain_text",
                                "content": "Generated by Blogger Radar",
                            }
                        ],
                    },
                ],
            },
        }

    def _sign(self, timestamp: str) -> str:
        """Generate Feishu bot signature (HMAC-SHA256 + base64)."""
        string_to_sign = f"{timestamp}\n{self.secret}"
        hmac_code = hmac.new(
            string_to_sign.encode("utf-8"),
            digestmod=hashlib.sha256,
        ).digest()
        return base64.b64encode(hmac_code).decode("utf-8")
