#!/usr/bin/env python3
"""
blogger-radar / scripts / pushers / slack_pusher.py
Push the daily report to a Slack channel via Incoming Webhooks.

Setup:
  1. Go to api.slack.com/apps → Create New App → From scratch
  2. Enable "Incoming Webhooks" and add to your workspace
  3. Copy the Webhook URL (starts with https://hooks.slack.com/services/...)
  4. Set SLACK_WEBHOOK_URL in your .env file

Config entry in ~/.blogger-radar/config.json:
  { "channel": "slack", "enabled": true }

Environment variable required:
  SLACK_WEBHOOK_URL
"""

import logging
from datetime import datetime

import httpx

log = logging.getLogger(__name__)

# Slack markdown is simpler than standard Markdown — truncate to stay under 3000 char block limit
BLOCK_CHAR_LIMIT = 2900


class SlackPusher:
    def __init__(self, cfg: dict) -> None:
        self.webhook_url = cfg.get("webhook_url", "")
        self.username = cfg.get("username", "Blogger Radar")
        self.icon_emoji = cfg.get("icon_emoji", ":satellite_antenna:")

    async def push(self, report: dict) -> bool:
        if not self.webhook_url:
            log.error("❌ SLACK_WEBHOOK_URL not set")
            return False

        markdown = report.get("markdown", "")
        date_str = report.get("date", datetime.now().strftime("%Y-%m-%d"))
        blogger_count = report.get("blogger_count", "?")

        blocks = self._build_blocks(markdown, date_str, blogger_count)

        payload = {
            "username": self.username,
            "icon_emoji": self.icon_emoji,
            "blocks": blocks,
        }

        try:
            async with httpx.AsyncClient(timeout=15) as client:
                resp = await client.post(self.webhook_url, json=payload)
                if resp.status_code == 200 and resp.text == "ok":
                    log.info("✓ Slack push success")
                    return True
                else:
                    log.error(f"✗ Slack returned {resp.status_code}: {resp.text}")
                    return False
        except Exception as e:
            log.error(f"✗ Slack push error: {e}")
            return False

    def _build_blocks(self, markdown: str, date_str: str, blogger_count) -> list:
        """Convert report markdown into Slack Block Kit blocks."""
        blocks = [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"📡 Blogger Radar — {date_str}",
                    "emoji": True,
                },
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": f"Tracking *{blogger_count}* creator(s) · Generated by Blogger Radar",
                    }
                ],
            },
            {"type": "divider"},
        ]

        # Split by blogger sections (## headers) and add each as a section block
        sections = markdown.split("\n## ")
        # Skip the report header (first chunk before any ## heading)
        for section in sections[1:]:
            lines = section.strip().splitlines()
            if not lines:
                continue
            title = lines[0].strip()
            body = "\n".join(lines[1:]).strip()

            blocks.append(
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": f"*{title}*",
                    },
                }
            )

            if body:
                # Truncate long bodies to stay within block limits
                if len(body) > BLOCK_CHAR_LIMIT:
                    body = body[:BLOCK_CHAR_LIMIT] + "\n_(truncated)_"
                blocks.append(
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": body,
                        },
                    }
                )
            blocks.append({"type": "divider"})

        return blocks
